backend:
  name: github
  repo: pennealpesto/pennealpesto.github.io
  branch: main
  # auth_type: implicit
  # app_id: Ov23liOfU4ISJWfWC6hj
  # login: true
  # roles: ["admin", "editor"]

media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "posts"
    label: "Posts"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    extension: "md"
    format: "frontmatter"

    fields:
      - label: "Layout"
        name: "layout"
        widget: "hidden"
        default: "post"

      - label: "Title"
        name: "title"
        widget: "string"

      - label: "Publish Date"
        name: "date"
        widget: "datetime"
        default: "{{now}}"
        format: "YYYY-MM-DD HH:mm:ss Z"

      - label: "Tags"
        name: "tags"
        widget: "list"
        allow_add: true
        field:
          label: "Tag"
          name: "tag"
          widget: "string"

      - label: "Images"
        name: "images"
        widget: "list"
        allow_add: true
        field:
          label: "Image"
          name: "image"
          widget: "image"

      - label: "Content"
        name: "content_text"
        widget: "markdown"

      - label: "Author"
        name: "author"
        widget: "string"
        default: "pennealpesto"

      - label: "Body"
        name: "body"
        widget: "hidden"
        default: |
          <!-- image + content injected in template -->
